Repository smu06030/issue-daily, pull requests merged in 2024-10, with the labels that each got.

#17 Feature/auth
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/google.png
  public/kakao.png
  src/app/(auth)/.gitkeep
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/login/route.ts
  src/app/api/logout/route.ts
  src/app/api/signup/route.ts
  src/app/page.tsx
  src/components/common/Button/GoogleButton.tsx
  src/components/common/Button/KakaoButton.tsx
  src/components/common/InputFeild/InputField.tsx
  src/utils/supabase/client.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
  tailwind.config.ts
Labels: 버그, 리팩토링, 기능 개발

#19 Feature/social login
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/login/route.ts
  src/app/api/signup/route.ts
  src/app/auth/callback/route.ts
  src/app/page.tsx
  src/components/common/Button/GoogleButton.tsx
  src/components/common/Button/KakaoButton.tsx
  src/middleware.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: 버그, 기능 개발

#23 Feat/mainPage 기능 구현 완료
  .gitignore
  package.json
  pnpm-lock.yaml
  public/news_image.jpg
  src/app/api/signup/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/.gitkeep
  src/components/Layout/Header.tsx
  src/components/common/InputFeild/InputField.tsx
  src/components/likes/LikeButton.tsx
  src/components/mainPage/CategoryNewsCard.tsx
  src/components/mainPage/CategoryNewsList.tsx
  src/components/mainPage/TopNewsCard.tsx
  src/components/mainPage/TopNewsList.tsx
  src/serverActions/.gitkeep
  src/serverActions/newsApi.ts
  src/types/.gitkeep
  src/types/NewsInfo.ts
  src/utils/category/categoryArr.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: 문서, 기능 개발

#25 [#14] feat: 댓글 crud
  db.json
  package.json
  pnpm-lock.yaml
  src/app/detail/[id]/AllComments.tsx
  src/app/detail/[id]/Comment.tsx
  src/app/detail/[id]/Comments.tsx
  src/app/detail/[id]/MyComments.tsx
  src/app/detail/[id]/page.tsx
  src/types/Comment.ts
Labels: 기능 개발

#26 fix: CategoryNewsCard
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/mainPage/CategoryNewsCard.tsx
Labels: 리팩토링

#27 Feature/reset password
  pnpm-lock.yaml
  src/app/(auth)/auth-layout.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/update-password/page.tsx
  src/app/api/auth.ts
  src/components/common/Form/LoginForm.tsx
  src/components/common/Form/ResetPasswordForm.tsx
  src/components/common/Form/SignUpForm.tsx
  src/components/common/Form/UpdatePasswordForm.tsx
  src/components/mainPage/CategoryNewsList.tsx
  src/components/mainPage/TopNewsList.tsx
  src/middleware.ts
Labels: 리팩토링, 기능 개발

#31 로그인, 회원가입 페이지 margin값 조정
  src/app/(auth)/login/page.tsx
  src/components/common/Form/ResetPasswordForm.tsx
  src/components/common/Form/SignUpForm.tsx
Labels: 스타일

#32 Feat/main page
  src/app/layout.tsx
  src/components/Layout/Header.tsx
  src/components/common/Form/LoginForm.tsx
  src/components/likes/LikeButton.tsx
  src/providers/userStoreProvider.tsx
  src/store/user-store.ts
Labels: 리팩토링

#33 Feat/detail page
  src/app/detail/[category]/[id]/AllComments.tsx
  src/app/detail/[category]/[id]/Comment.tsx
  src/app/detail/[category]/[id]/Comments.tsx
  src/app/detail/[category]/[id]/MyComments.tsx
  src/app/detail/[category]/[id]/page.tsx
  src/app/detail/[id]/Comments.tsx
  src/app/detail/[id]/page.tsx
  src/components/mainPage/CategoryNewsCard.tsx
  src/types/Comment.ts
Labels: 폴더, 기능 개발, 스타일

#34 Feat/detail page
  src/app/detail/[category]/[id]/Comments.tsx
  src/components/mainPage/TopNewsCard.tsx
Labels: 버그

#35 Feat/mypage
  src/app/(root)/(protected)/mypage/page.tsx
  src/app/detail/[category]/[id]/AllComments.tsx
  src/app/detail/[category]/[id]/Comment.tsx
  src/app/detail/[category]/[id]/MyComments.tsx
  src/components/Layout/Header.tsx
  src/components/common/Button/LogoutButton.tsx
  src/components/likes/LikeButton.tsx
  src/components/mypage/Card.tsx
  src/components/mypage/Comment.tsx
  src/components/mypage/Likes.tsx
  src/components/mypage/Modal.tsx
  src/components/mypage/Profile.tsx
Labels: 버그, 리팩토링

#36 fix: middleware, zustand 수정 및 loading UI 추가
  src/app/(auth)/auth-layout.tsx
  src/app/(auth)/loading.tsx
  src/app/layout.tsx
  src/components/common/Button/GoogleButton.tsx
  src/components/common/Button/KakaoButton.tsx
  src/components/mypage/Likes.tsx
  src/middleware.ts
  src/providers/userStoreProvider.tsx
  src/store/user-store.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: 버그, 리팩토링

#37 병합 후 기능 최종 확인
  src/app/(root)/detail/[category]/[id]/AllComments.tsx
  src/app/(root)/detail/[category]/[id]/Comment.tsx
  src/app/(root)/detail/[category]/[id]/Comments.tsx
  src/app/(root)/detail/[category]/[id]/MyComments.tsx
  src/app/(root)/detail/[category]/[id]/page.tsx
  src/app/layout.tsx
  src/components/Layout/Header.tsx
  src/components/common/Button/GoogleButton.tsx
  src/components/common/Button/KakaoButton.tsx
  src/components/common/Button/LogoutButton.tsx
  src/components/likes/LikeButton.tsx
  src/components/mainPage/CategoryNewsCard.tsx
  src/components/mainPage/CategoryNewsList.tsx
  src/components/mainPage/TopNewsCard.tsx
  src/components/mypage/Card.tsx
  src/components/mypage/Likes.tsx
  src/components/mypage/Modal.tsx
  src/providers/userStoreProvider.tsx
  src/public/google.png
  src/public/images/default_img.jpg
  src/public/images/default_profile.jpeg
  src/public/kakao.png
  src/public/news_image.jpg
  src/serverActions/newsApi.ts
Labels: 리팩토링, 폴더, 스타일

#47 fix: 로그아웃 시에 댓글 등록 x, types 와 serverActions 코드 분리
  src/app/(root)/detail/[category]/[id]/AllComments.tsx
  src/app/(root)/detail/[category]/[id]/Comments.tsx
  src/app/(root)/detail/[category]/[id]/MyComments.tsx
  src/app/(root)/detail/[category]/[id]/page.tsx
  src/serverActions/commentsActions.ts
  src/types/comment.ts
Labels: 버그, 리팩토링
